name: test-unit

"on":
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

jobs:
  test:
    name: unit-flow-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: bats-core をセットアップ
        shell: bash
        run: bash ./scripts/install-bats.sh

      - name: 単体テスト
        shell: bash
        run: |
          bash ./tests/bin/bats tests/unit

      - name: フローテスト
        shell: bash
        run: |
          bash ./tests/bin/bats tests/flow
